services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: